POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pa2tpIiwiaWQiOiI2NDUxNTgyZDM0MmZlY2EwOWUwMWRlZWIiLCJpYXQiOjE2ODUzMzUxMzJ9.GpwAZ8ygCOis9gU3SBIxa3Y_2KfQX0USvv2fr7L2Q5o

{
    "title": "testi3",
    "author": "someone",
    "url": "urlosoite",
    "likes": 10,
    "userId": "6451582d342feca09e01deeb"
}