DELETE http://localhost:3001/api/blogs/64524a87c4d919ec3732de4a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFrdWFua2thIiwiaWQiOiI2NDRhNWZiNTdlMTM0ZDQ0YTJkNDFkZjMiLCJpYXQiOjE2ODMxMTY2NzAsImV4cCI6MTY4MzEyMDI3MH0.55L2tMxBhrAt0NtpUkTt3ODhScwbI68ApBW5_Qy5nHM
